"""Added SessionFiles

Revision ID: 04bd6355dfb7
Revises: 806ebe544d35
Create Date: 2025-10-01 17:59:59.900791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04bd6355dfb7'
down_revision: Union[str, None] = '806ebe544d35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_files', sa.Column('password', sa.String(length=200), nullable=True))
    op.add_column('session_files', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_files', 'created_at')
    op.drop_column('session_files', 'password')
    # ### end Alembic commands ###
