"""implemented more currency changes

Revision ID: 0aa3b8da9b64
Revises: b09dc4806baa
Create Date: 2025-10-29 17:45:47.271068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aa3b8da9b64'
down_revision: Union[str, None] = 'b09dc4806baa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session_accounts', 'bank_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('session_accounts', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('session_accounts', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('session_accounts', 'bank_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
