"""Added

Revision ID: 1dbcf2864bde
Revises: 2a64a5b55d67
Create Date: 2025-07-16 19:14:50.688332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dbcf2864bde'
down_revision: Union[str, None] = '2a64a5b55d67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banks', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('banks', sa.Column('auth_method', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('banks', 'auth_method')
    op.drop_column('banks', 'active')
    # ### end Alembic commands ###
