"""Added

Revision ID: 2a64a5b55d67
Revises: d2bc81d5c347
Create Date: 2025-07-16 18:00:55.004771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a64a5b55d67'
down_revision: Union[str, None] = 'd2bc81d5c347'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('banks', sa.Column('bank_account_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('banks', 'bank_account_type')
    # ### end Alembic commands ###
