"""Added Cascad to delete transactions

Revision ID: 2c6ca10fdf67
Revises: 6a1b34c6e094
Create Date: 2025-06-21 14:13:33.039157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c6ca10fdf67'
down_revision: Union[str, None] = '6a1b34c6e094'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
