"""transaction insights

Revision ID: 48b5ba5ba61b
Revises: 8b4b2c41fcee
Create Date: 2025-09-12 16:46:19.029121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '48b5ba5ba61b'
down_revision: Union[str, None] = '8b4b2c41fcee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_cmetadata_gin'), table_name='langchain_pg_embedding', postgresql_ops={'cmetadata': 'jsonb_path_ops'}, postgresql_using='gin')
    # op.drop_table('langchain_pg_embedding')
    # op.drop_table('langchain_pg_collection')
    op.add_column('transaction_insights', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('transaction_insights', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('transaction_insights', sa.Column('is_lastest', sa.Boolean(), nullable=False))
    op.alter_column('transaction_insights', 'insight',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction_insights', 'insight',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('transaction_insights', 'is_lastest')
    op.drop_column('transaction_insights', 'updated_at')
    op.drop_column('transaction_insights', 'created_at')
    # op.create_table('langchain_pg_collection',
    # sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    # sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    # sa.Column('cmetadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    # sa.PrimaryKeyConstraint('uuid', name='langchain_pg_collection_pkey'),
    # sa.UniqueConstraint('name', name='langchain_pg_collection_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    # postgresql_ignore_search_path=False
    # )
    # op.create_table('langchain_pg_embedding',
    # sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    # sa.Column('collection_id', sa.UUID(), autoincrement=False, nullable=True),
    # # sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(), autoincrement=False, nullable=True),
    # sa.Column('document', sa.VARCHAR(), autoincrement=False, nullable=True),
    # sa.Column('cmetadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    # sa.ForeignKeyConstraint(['collection_id'], ['langchain_pg_collection.uuid'], name=op.f('langchain_pg_embedding_collection_id_fkey'), ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('id', name=op.f('langchain_pg_embedding_pkey'))
    # )
    # op.create_index(op.f('ix_cmetadata_gin'), 'langchain_pg_embedding', ['cmetadata'], unique=False, postgresql_ops={'cmetadata': 'jsonb_path_ops'}, postgresql_using='gin')
    # ### end Alembic commands ###
