"""removed unique for transactions

Revision ID: 4e3ed886278b
Revises: b85899f10a85
Create Date: 2025-09-23 19:25:14.673079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e3ed886278b'
down_revision: Union[str, None] = 'b85899f10a85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('session_transactions_transaction_id_key'), 'session_transactions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('session_transactions_transaction_id_key'), 'session_transactions', ['transaction_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
