"""added payment stores

Revision ID: 5ba63b34b3b3
Revises: c2c824f8d98c
Create Date: 2025-10-21 20:27:18.484180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ba63b34b3b3'
down_revision: Union[str, None] = 'c2c824f8d98c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_payment_stores', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('sessions', sa.Column('paid', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'paid')
    op.drop_column('session_payment_stores', 'updated_at')
    # ### end Alembic commands ###
