"""changed bank code to false

Revision ID: 6d6a3c0b8da6
Revises: b9baefde4645
Create Date: 2025-07-15 21:27:15.701436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d6a3c0b8da6'
down_revision: Union[str, None] = 'b9baefde4645'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('banks_bank_code_key', 'banks', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('banks_bank_code_key', 'banks', ['bank_code'])
    # ### end Alembic commands ###
