"""added indexed

Revision ID: 7020d462454e
Revises: c0a7eaccfcc1
Create Date: 2025-06-17 23:54:17.984925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7020d462454e'
down_revision: Union[str, None] = 'c0a7eaccfcc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('indexed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'indexed')
    # ### end Alembic commands ###
