"""added currency_code to session and set default to usd

Revision ID: 7bbf82198154
Revises: 0aa3b8da9b64
Create Date: 2025-10-31 16:41:37.061803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bbf82198154'
down_revision: Union[str, None] = '0aa3b8da9b64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('currency_code', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'currency_code')
    # ### end Alembic commands ###
