"""create embeddings

Revision ID: 7ebda89857ac
Revises: c2dc2c25a1f0
Create Date: 2025-08-06 17:52:21.715445

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ebda89857ac'
down_revision: Union[str, None] = 'c2dc2c25a1f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('messages')
    # op.add_column('transactions', sa.Column('embedding', Vector(dim=1536), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('transactions', 'embedding')
    # op.create_table('messages',
    # sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    # sa.Column('response', sa.VARCHAR(), autoincrement=False, nullable=True),
    # sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='messages_user_id_fkey'),
    # sa.PrimaryKeyConstraint('id', name='messages_pkey')
    # )
    # ### end Alembic commands ###
