"""added

Revision ID: 8fcde0ec45fa
Revises: c70c254e1696
Create Date: 2025-06-18 23:15:09.960487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fcde0ec45fa'
down_revision: Union[str, None] = 'c70c254e1696'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('last_synced', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'last_synced')
    # ### end Alembic commands ###
