"""Added Indexed Session to Chroma Db

Revision ID: 9986181553f4
Revises: a4bfb79491a2
Create Date: 2025-10-10 13:43:01.689044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9986181553f4'
down_revision: Union[str, None] = 'a4bfb79491a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('indexed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'indexed')
    # ### end Alembic commands ###
