"""Session SWOT, Insights, Savings Potential and Assessment Model data generated

Revision ID: 9b81b008091e
Revises: 4e3ed886278b
Create Date: 2025-09-28 15:00:15.918649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b81b008091e'
down_revision: Union[str, None] = '4e3ed886278b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('savings_potentials')
    op.drop_table('savings_potentials_sessions')
    op.add_column('session_swots', sa.Column('swot_type', sa.String(), nullable=False))
    op.drop_column('session_swots', 'type')
    op.add_column('sessions', sa.Column('customer_type', sa.String(length=50), nullable=True))
    op.add_column('sessions', sa.Column('overall_assessment', sa.String(), nullable=True))
    op.add_column('sessions', sa.Column('overall_assessment_title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'overall_assessment_title')
    op.drop_column('sessions', 'overall_assessment')
    op.drop_column('sessions', 'customer_type')
    op.add_column('session_swots', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('session_swots', 'swot_type')
    op.create_table('savings_potentials_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('potential', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('savings_potentials_sessions_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('savings_potentials_sessions_pkey'))
    )
    op.create_table('savings_potentials',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('potential', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('savings_potentials_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('savings_potentials_pkey'))
    )
    # ### end Alembic commands ###
