"""changed type to insight type

Revision ID: a9ff795e5e68
Revises: d44a9b37ff80
Create Date: 2025-09-12 17:24:25.919314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9ff795e5e68'
down_revision: Union[str, None] = 'd44a9b37ff80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('transaction_insights', sa.Column('insight_type', sa.String(), nullable=False))
    # op.drop_column('transaction_insights', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('transaction_insights', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    # op.drop_column('transaction_insights', 'insight_type')
    # ### end Alembic commands ###
