"""changed country column number from 10 to 200

Revision ID: b09dc4806baa
Revises: d4dbd8ec9af5
Create Date: 2025-10-29 15:37:52.350360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b09dc4806baa'
down_revision: Union[str, None] = 'd4dbd8ec9af5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('currencies', 'country',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=200),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('currencies', 'country',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###
