"""removed unique

Revision ID: b85899f10a85
Revises: 9d53318c8911
Create Date: 2025-09-23 19:23:15.795678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b85899f10a85'
down_revision: Union[str, None] = '9d53318c8911'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('session_accounts_account_number_key'), 'session_accounts', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('session_accounts_account_number_key'), 'session_accounts', ['account_number'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
