"""transaction insights change column to is_latest

Revision ID: bf02aa2f5db1
Revises: 48b5ba5ba61b
Create Date: 2025-09-12 16:53:43.880067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf02aa2f5db1'
down_revision: Union[str, None] = '48b5ba5ba61b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('transaction_insights', sa.Column('is_latest', sa.Boolean(), nullable=False))
    # op.drop_column('transaction_insights', 'is_lastest')
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('transaction_insights', sa.Column('is_lastest', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # op.drop_column('transaction_insights', 'is_latest')
    # ### end Alembic commands ###
