"""Added account id from mono to accounts

Revision ID: c0a7eaccfcc1
Revises: a3881590e2e0
Create Date: 2025-06-14 22:33:32.669529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0a7eaccfcc1'
down_revision: Union[str, None] = 'a3881590e2e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('account_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'account_id')
    # ### end Alembic commands ###
