"""added bank_ids to bank file

Revision ID: c2c824f8d98c
Revises: 9986181553f4
Create Date: 2025-10-18 13:06:18.979351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2c824f8d98c'
down_revision: Union[str, None] = '9986181553f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_files', sa.Column('bank_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'session_files', 'banks', ['bank_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'session_files', type_='foreignkey')
    op.drop_column('session_files', 'bank_id')
    # ### end Alembic commands ###
