"""added processing status to session

Revision ID: c671280e5250
Revises: 9b81b008091e
Create Date: 2025-09-28 15:13:08.223194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c671280e5250'
down_revision: Union[str, None] = '9b81b008091e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_financial_data')
    op.add_column('sessions', sa.Column('processing_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'processing_status')
    op.create_table('session_financial_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('liquidity_risk', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('concentration_risk', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('session_financial_data_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('session_financial_data_pkey'))
    )
    # ### end Alembic commands ###
