"""made changes to transactions

Revision ID: c70c254e1696
Revises: 7020d462454e
Create Date: 2025-06-18 00:02:49.595139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c70c254e1696'
down_revision: Union[str, None] = '7020d462454e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('transaction_id', sa.String(length=200), nullable=False))
    op.add_column('transactions', sa.Column('currency', sa.String(length=10), nullable=False))
    op.add_column('transactions', sa.Column('date', sa.DateTime(), nullable=False))
    op.add_column('transactions', sa.Column('balance_after_transaction', sa.Float(), nullable=False))
    op.create_unique_constraint(None, 'transactions', ['transaction_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='unique')
    op.drop_column('transactions', 'balance_after_transaction')
    op.drop_column('transactions', 'date')
    op.drop_column('transactions', 'currency')
    op.drop_column('transactions', 'transaction_id')
    # ### end Alembic commands ###
