"""changed bank name unique to false

Revision ID: d2bc81d5c347
Revises: 6d6a3c0b8da6
Create Date: 2025-07-15 21:27:57.421808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2bc81d5c347'
down_revision: Union[str, None] = '6d6a3c0b8da6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('banks_bank_name_key', 'banks', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('banks_bank_name_key', 'banks', ['bank_name'])
    # ### end Alembic commands ###
