"""added more columns to insight

Revision ID: d44a9b37ff80
Revises: bf02aa2f5db1
Create Date: 2025-09-12 17:21:48.418024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd44a9b37ff80'
down_revision: Union[str, None] = 'bf02aa2f5db1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('transaction_insights', sa.Column('title', sa.String(length=200), nullable=False))
    # op.add_column('transaction_insights', sa.Column('priority', sa.String(), nullable=False))
    # op.add_column('transaction_insights', sa.Column('type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('transaction_insights', 'type')
    # op.drop_column('transaction_insights', 'priority')
    # op.drop_column('transaction_insights', 'title')
    # ### end Alembic commands ###
