"""added reference to payment stores

Revision ID: e30b3573fbbe
Revises: 5ba63b34b3b3
Create Date: 2025-10-21 20:49:58.161364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e30b3573fbbe'
down_revision: Union[str, None] = '5ba63b34b3b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_payment_stores', sa.Column('payment_reference', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_payment_stores', 'payment_reference')
    # ### end Alembic commands ###
