"""Reverted back and fixed issues

Revision ID: ee0f7928f1a2
Revises: 37820bd776ca
Create Date: 2025-08-07 21:14:18.876470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee0f7928f1a2'
down_revision: Union[str, None] = '37820bd776ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
